import React from 'react';
import { Download, Share2, Sparkles, RefreshCw } from 'lucide-react';
import { Button } from './Button';

interface ResultDisplayProps {
  imageSrc: string | null;
  isLoading: boolean;
  onDownload: () => void;
  onRetry: () => void;
}

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ imageSrc, isLoading, onDownload, onRetry }) => {
  
  if (isLoading) {
    return (
      <div className="w-full h-full min-h-[300px] bg-slate-50 rounded-xl border-2 border-slate-200 flex flex-col items-center justify-center p-8 animate-pulse">
        <div className="w-16 h-16 bg-indigo-200 rounded-full mb-4 animate-bounce flex items-center justify-center">
            <Sparkles className="w-8 h-8 text-indigo-500" />
        </div>
        <h3 className="text-lg font-semibold text-slate-700 mb-2">Magic in progress...</h3>
        <p className="text-slate-500 text-center max-w-xs">
          Gemini is reimagining your image. This might take a few seconds.
        </p>
      </div>
    );
  }

  if (!imageSrc) {
    return (
      <div className="w-full h-full min-h-[300px] bg-slate-50 rounded-xl border-2 border-dashed border-slate-300 flex flex-col items-center justify-center p-8 opacity-60">
        <ImageIconPlaceholder />
        <p className="text-slate-500 mt-4 text-center">
          Your edited image will appear here
        </p>
      </div>
    );
  }

  return (
    <div className="relative group w-full h-full min-h-[300px] bg-slate-900 rounded-xl overflow-hidden border border-slate-800 flex items-center justify-center shadow-2xl">
      <img 
        src={imageSrc} 
        alt="Generated Result" 
        className="w-full h-full object-contain max-h-[500px]"
      />
      
      <div className="absolute top-0 left-0 right-0 p-4 bg-gradient-to-b from-black/70 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex justify-between">
        <span className="text-white font-medium text-sm flex items-center">
            <Sparkles className="w-4 h-4 mr-2 text-yellow-400" /> Generated by Gemini 2.5
        </span>
      </div>

      <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black/80 via-black/40 to-transparent opacity-100 flex justify-center gap-3">
         <Button onClick={onDownload} variant="primary" icon={<Download size={16} />} className="shadow-lg">
           Download
         </Button>
         <button onClick={onRetry} className="bg-white/10 hover:bg-white/20 text-white p-2.5 rounded-lg backdrop-blur-md transition-colors border border-white/10">
            <RefreshCw size={20} />
         </button>
      </div>
    </div>
  );
};

const ImageIconPlaceholder = () => (
  <svg className="w-16 h-16 text-slate-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round">
    <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
    <circle cx="8.5" cy="8.5" r="1.5"></circle>
    <polyline points="21 15 16 10 5 21"></polyline>
  </svg>
);
